language: node_js

node_js:
  - "7"
  - "8"

matrix:
  include:
    - node_js: "8"
      env: BUILD_DOCS=true

cache:
  directories:
    - node_modules

install: npm install

script:
  - bash ./deploy/deploy.sh

env:
  global:
    - ENCRYPTION_LABEL: "40c022fcc411"

