language: node_js
node_js:
  - "8"
cache:
  directories:
    - node_modules
install: npm install
script:
  - bash ./deploy/deploy.sh
env:
  global:
    - ENCRYPTION_LABEL: "583a5951da37"
    - COMMIT_AUTHOR_EMAIL: "amishshah.2k@gmail.com"
dist: trusty
sudo: false
