language: node_js

node_js:
  - "7"
  - "8"

matrix:
  include:
    - node_js: "8"
      env: BUILD_DOCS=true

branches:
  only:
  - gh-pages-src
  - /.*/

cache:
  yarn: true
  directories:
    - node_modules

script:
  - bash ./deploy/deploy.sh

env:
  global:
    - ENCRYPTION_LABEL: "40c022fcc411"
