language: node_js

node_js:
  - "9"

branches:
  only:
  - gh-pages-src
  - /.*/

cache:
  directories:
    - node_modules

install: npm install

script:
  - bash ./deploy/deploy.sh

env:
  global:
    - ENCRYPTION_LABEL: "40c022fcc411"
