language: node_js
node_js:
  - "7"
  - "8"
cache:
  directories:
    - node_modules
install: npm install
script:
  - bash ./deploy/deploy.sh
env:
  global:
    - ENCRYPTION_LABEL: "40c022fcc411"
dist: trusty
sudo: false
